version: '2'
services:
  yx-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: always
    ports:
    - 9001:9001

  yx-config:
    links:
      - yx-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-config
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: always

  yx-monitor:
    links:
    - yx-eureka:eureka
    build:
      context: ./
      dockerfile: Dockerfile-monitor
    environment:
    - "SPRING_PROFILES_ACTIVE=prod"
    restart: always