version: '2'
services:
  yx-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
    - 9001:9001

  pig-config:
    links:
    - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always