version: '2'
services:
  yx-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
    - 9001:9001
  yx-config:
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    ports:
    - 9002:9002